apiVersion: apps/v1
kind: Deployment
metadata:
  name: customdbv1
  namespace: liqooff
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customdbv1
  template:
    metadata:
      labels:
        app: customdbv1
    spec:
      containers:
      - name: customdbv1
        image: mysql:5.6
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: '{{ parameter "/password" }}'
        ports:
        - containerPort: 3306
          name: mysql