---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-broker
  labels:
    app: service-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-broker
  template:
    metadata:
      labels:
        app: service-broker
    spec:
      containers:
      - args:
        - -logtostderr
        - -v
        - "1"
        # This may be either 'basic' (for username/password), or token (for bearer token)
        # If you change this, then you also need to update the authentication type defined
        # in clusterservicebroker.yaml
        - -authentication=token
        - -token=/var/run/secrets/service-broker/token
        - -username=/var/run/secrets/service-broker/username
        - -password=/var/run/secrets/service-broker/password
        - -tls-certificate=/var/run/secrets/service-broker/tls-certificate
        - -tls-private-key=/var/run/secrets/service-broker/tls-private-key
        name: service-broker
        image: localhost:5001/service-broker:latest
        env:
        - name: NAMESPACE
          value: default
        volumeMounts:
        - mountPath: /var/run/secrets/service-broker
          name: secret-volume
          readOnly: true
        ports:
        - containerPort: 8443
      serviceAccountName: service-broker
      volumes:
      - name: secret-volume
        secret:
          secretName: service-broker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: psltest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432  # Exposes container port
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the postgres application
  selector:
    app: postgres