---
apiVersion: v1
kind: Service
metadata:
  name: service-broker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: service-broker
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443